name: button_uz
description: This button provides many conveniences. These are with, height, margin, border, raduis and others.
version: 0.0.3
author: Sunnatillo Shavkatov <sunnatilloshavkatov@gmail.com>  
homepage: https://github.com/SunnatilloQuantic/flutter_buttom

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: