name: button_uz
description: This button provides many conveniences. These are with, height, margin, border, raduis and others.
version: 0.0.1
# authors: Sunnatillo Shavkatov
homepage: https://github.com/SunnatilloQuantic/flutter_buttom

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: